In [4]:
import numpy as np



def gen_mat_vander(invector , n, increasing = False):
    if not increasing:
        out_mat = np.array([x**(n-1-i) for x in invector for i in range(n)]).reshape(invector.size ,n)
    elif  increasing:
        out_mat = np.array([x**i for x in invector for i in range(n)]).reshape(invector.size,n)
    return out_mat



inpvect = np.array([1,3,5,7,9,11])
no_col = 5

outmat_increasing = gen_mat_vander(inpvect, no_col ,True)

outmat_decreasing =gen_mat_vander(inpvect ,no_col , False)


print("Entered array is:",inpvect,"\n")
print("Number of columns in output matrix :",no_col,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",outmat_increasing ,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",outmat_decreasing,"\n")


Entered array is: [ 1  3  5  7  9 11] 

Number of columns in output matrix : 5 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     3     9    27    81]
 [    1     5    25   125   625]
 [    1     7    49   343  2401]
 [    1     9    81   729  6561]
 [    1    11   121  1331 14641]] 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   81    27     9     3     1]
 [  625   125    25     5     1]
 [ 2401   343    49     7     1]
 [ 6561   729    81     9     1]
 [14641  1331   121    11     1]] 



In [19]:
import numpy as np


def moving_avg(a, window =3) :
    output = np.cumsum(a, dtype=float)
    output[window:] = output[window:] - output[:-window]
    return output[window - 1:] / window


test = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_avg(test, window=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
